#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


#time: 3 hours

second_antecessor = 1
first_antecessor = 2
main_number = second_antecessor + first_antecessor
total = 2
while main_number < 4000000
    puts "#{main_number} => #{total}"
    total += main_number if main_number.even?
    second_antecessor = first_antecessor
    first_antecessor = main_number
    main_number = second_antecessor + first_antecessor
end

puts total
